### ISSUE TITLE
error with no context

### ISSUE THREAD

**Issue by DDR0** [anura-engine/anura#248]
Console:
```
void main()
{
v_texcoord = a_anura_texcoord;
gl_Position = u_anura_mvp_matrix * a_anura_vertex;
}
"
})
INFO: ShadersOGL.cpp:1767 : Added shader: 0669395e069643bf84067cd98133658a
INFO: controls.cpp:198 : SET STARTING CYCLES: 0
INFO: editor.cpp:930 : BEGIN EDITOR::EDITOR
INFO: editor.cpp:943 : TileMap::loadAll(): 566ms
INFO: editor.cpp:945 : tileset::init(): 1ms
WARN: RenderManager.cpp:45 : Replacing queue Level::opaques at priority 0 with queue Level::opaques
INFO: level.cpp:382 : in level constructor...
INFO: level.cpp:494 : building...3415
INFO: level.cpp:504 : done building...3415
INFO: level.cpp:531 : LAYER -45 BUILT 1136 tiles
INFO: level.cpp:531 : LAYER -28 BUILT 20 tiles
INFO: level.cpp:534 : done building tile_map...3418
INFO: level.cpp:669 : done level constructor: 4
INFO: controls.cpp:198 : SET STARTING CYCLES: 0
INFO: FontSDL.cpp:60 : Compiled with SDL_ttf version: 2.0.14
INFO: FontSDL.cpp:61 : Linked   with SDL_ttf version: 2.0.14
INFO: editor.cpp:973 : END EDITOR::EDITOR: 573ms
INFO: editor.cpp:1264 : EDITOR RESOLUTION MANAGER: 0, 0
INFO: editor.cpp:1288 : EDITOR RESOLUTION: 2820,1480
INFO: editor.cpp:3358 : CHANGE TOOL: 0
INFO: FboOGL.cpp:325 : rebuild fbo to 2820,1480
INFO: editor.cpp:3358 : CHANGE TOOL: 5
libpng warning: iCCP: known incorrect sRGB profile
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
[1]    12420 abort (core dumped)  ./anura --level=test2.cfg --edit --error_message_box=false
134 in  ~/anura git:(trunk)  
$ 
```

Here is a backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4ce0f5d in __GI_abort () at abort.c:90
#2  0x00007ffff5687095 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5684c86 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5684cd1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5684f14 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff56ae8df in std::__throw_length_error(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff571a68c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x0000555555cea55a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (
    this=this@entry=0x7fffffffa430, __beg=40 '(', __end=...) at /usr/include/c++/7/bits/basic_string.tcc:219
#9  0x0000555555d20483 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (
    __end=..., __beg=..., this=0x7fffffffa430) at /usr/include/c++/7/bits/basic_string.h:236
#10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (__end=..., __beg=..., 
    this=0x7fffffffa430) at /usr/include/c++/7/bits/basic_string.h:255
#11 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, void> (__a=..., __end=..., __beg=..., 
    this=0x7fffffffa430) at /usr/include/c++/7/bits/basic_string.h:607
#12 game_logic::(anonymous namespace)::parse_function_def (callable_def=..., symbols=
    0x555556b10120 <get_custom_object_functions_symbol_table()::table>, i2=0x55555dd28d90, i1=@0x7fffffffa0d8: 0x55555dd28d90, 
    formula_str=..., this=<optimised out>, this=<optimised out>, this=<optimised out>, this=<optimised out>, 
    this=<optimised out>, this=<optimised out>, this=<optimised out>, this=<optimised out>, this=<optimised out>, 
    this=<optimised out>, this=<optimised out>, this=<optimised out>) at src/formula.cpp:4195
#13 game_logic::(anonymous namespace)::parse_expression_internal (formula_str=..., i1=<optimised out>, i1@entry=0x55555dd28ca0, 
    i2=i2@entry=0x55555dd28d90, symbols=0x555556b10120 <get_custom_object_functions_symbol_table()::table>, callable_def=..., 
    can_optimize=<optimised out>) at src/formula.cpp:4393
#14 0x0000555555d30510 in game_logic::(anonymous namespace)::parse_expression (formula_str=..., i1=i1@entry=0x55555dd28ca0, 
    i2=i2@entry=0x55555dd28d90, symbols=symbols@entry=0x555556b10120 <get_custom_object_functions_symbol_table()::table>, 
    callable_def=..., can_optimize=0x0) at src/formula.cpp:4122
#15 0x0000555555d31bd1 in game_logic::Formula::Formula (this=0x55555dd2e110, val=..., 
    symbols=0x555556b10120 <get_custom_object_functions_symbol_table()::table>, callableDefinition=...) at src/formula.cpp:5054
#16 0x0000555555d34060 in game_logic::Formula::createOptionalFormula (val=...,                                                     
    symbols=0x555556b10120 <get_custom_object_functions_symbol_table()::table>, callableDefinition=...,                            
    lang=lang@entry=game_logic::Formula::FORMULA_LANGUAGE::FFL) at src/formula.cpp:4939                                            
#17 0x0000555555e34bd0 in CustomObjectType::CustomObjectType (this=0x55555dcf9490, id=..., node=..., base_type=0x0,                
    old_type=<optimised out>) at src/custom_object_type.cpp:1630                                                                   
#18 0x0000555555e3b4b4 in CustomObjectType::recreate (id="frogatto:dialog_controller", old_type=old_type@entry=0x0)                
    at src/custom_object_type.cpp:930                                                                                              
#19 0x0000555555e3c47f in CustomObjectType::create (id="frogatto:dialog_controller") at src/custom_object_type.cpp:891             
#20 0x0000555555e3fc42 in CustomObjectType::get (id="frogatto:dialog_controller") at src/custom_object_type.cpp:857                
#21 0x0000555555ea2290 in CustomObject::CustomObject (this=0x55555dcf0d20, node=...) at src/custom_object.cpp:209                  
#22 0x0000555556263310 in Entity::build (node=...) at src/entity.cpp:138                                                           
#23 0x0000555555d77f9a in editor::enemy_type::preview_object (this=0x55555d4769a0) at src/editor.cpp:811                           
#24 0x0000555555d9bb1c in (anonymous namespace)::BuiltinEditor::draw_gui (this=0x55555b2af8d0) at src/editor.cpp:3634              
#25 0x0000555555f1fb0d in LevelRunner::play_cycle (this=this@entry=0x7fffffffd520) at src/level_runner.cpp:1863                    
#26 0x0000555555f2481a in LevelRunner::play_level (this=0x7fffffffd520) at src/level_runner.cpp:892                                
#27 0x00005555558e8406 in main (argcount=<optimised out>, argvec=<optimised out>) at src/main.cpp:1241 
```

**Comment by DDR0** [comment]
fixed by b4cb09f6f5784defd414f6ca9e9f0a75fd780d58.
